### ISSUE TITLE
Cannot build from master branch using CMake

### ISSUE THREAD

**Issue by rpep** [exafmm/exafmm-beta#44]
Is CMake building supported, or has this been deprecated in favour of using GNU Autoconf? I couldn't get Exafmm to build using CMake, with the problems seemingly due to changes in the setup - the macro EXPANSION looks like it's been replaced with EXAFMM_EXPANSION for example.

**Comment by pizzooid** [comment]
afaik CMake is not supported; Autoconf is used by all the test scripts

**Comment by rpep** [comment]
OK, would you like me to make a pull request to remove the CMake related files then? This was a bit of a source of confusion for me trying to build the software.

**Comment by rioyokota** [comment]
Removed Cmake and merged the develop branch into master
