### ISSUE TITLE
Compilation crashes with (at least?) inlining failed in call to always_inline

### ISSUE THREAD

**Issue by maxlevesque** [exafmm/exafmm-beta#47]
Hi,

I wanted to test your FMM implementation but it fails to compile. Here is what I did:
```sh
git clone https://github.com/exafmm/exafmm.git
cd exafmm
./configure # Seems fine. No error message nor warnings. See https://gist.github.com/maxlevesque/c196a51842eaacabaa1af074bd4bca43
make
```

Sadly, make reports the following error:
```sh
make  all-recursive
make[1]: Entering directory '/tmp/exafmm'
Making all in examples
make[2]: Entering directory '/tmp/exafmm/examples'
g++ -DHAVE_CONFIG_H -I. -I..  -I../include -I../vectorclass -I../kernels   -DEXAFMM_USE_SIMD        -DNDEBUG -DEXAFMM_PMAX=10  -ffast-math -funroll-loops -fabi-version=6 -Wfatal-errors          -MT fmm-fmm.o -MD -MP -MF .deps/fmm-fmm.Tpo -c -o fmm-fmm.o `test -f 'fmm.cxx' || echo './'`fmm.cxx
In file included from ../include/vec.h:1220:0,
                 from ../include/types.h:9,
                 from ../include/args.h:10,
                 from fmm.cxx:1:
/usr/lib/gcc/x86_64-linux-gnu/6/include/pmmintrin.h: In function ‘double exafmm::sum(const exafmm::vec<2, double>&)’:
/usr/lib/gcc/x86_64-linux-gnu/6/include/pmmintrin.h:86:1: error: inlining failed in call to always_inline ‘__m128d exafmm::_mm_hadd_pd(__m128d, __m128d)’: target specific option mismatch
 _mm_hadd_pd (__m128d __X, __m128d __Y)
 ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
Makefile:648: recipe for target 'fmm-fmm.o' failed
make[2]: *** [fmm-fmm.o] Error 1
make[2]: Leaving directory '/tmp/exafmm/examples'
Makefile:374: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/exafmm'
Makefile:314: recipe for target 'all' failed
make: *** [all] Error 2
```

Of course, I read the INSTALL file, but found nothing to be of help in this case. I also tested branch develop and same problem there.

I wish this report can be useful. Please don't hesitate if I can help in any way.

**Comment by rioyokota** [comment]
You don't seem to have any SSE or AVX flags.
If you would like to use SIMD intrinsics, use --enable-sse3 or --enable-avx with ./configure.
If you don't want to use SIMD, use --disable-simd with ./configure.
I should make the default use at least SSE3.

**Comment by rioyokota** [comment]
I have updated both master and develop branches so that SSE3 is enabled by default.
I cannot confirm that it works in your environment though.
If you would like exaFMM to run verification tests on your machine every time someone pushes to GitHub, I can setup a buildbot entry for you.
So far, exaFMM is being tested on the following machines:
http://login.rio.gsic.titech.ac.jp/waterfall

**Comment by maxlevesque** [comment]
my _/proc/cpuinfo_ reports
```sh
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
```
that includes all sse up to 4_1, avx and avx2.

I cloned the new master (and develop) branches.
I tested `./configure` without options and with `--disable-simd`, `-enable-sse3` and `enable-avx`.
I now have the following error message during `make`
```sh
In file included from vec.cxx:5:0:
../include/vec.h:813:55: note: #pragma message: Overloading vector operators for AVX
 #pragma message("Overloading vector operators for AVX")
                                                       ^
../include/vec.h:1218:55: note: #pragma message: Overloading vector operators for SSE
 #pragma message("Overloading vector operators for SSE")
                                                       ^
vec.cxx:50:28: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float SIMD<8, float>::EPS’ of non-integral type [-fpermissive]
   static const float EPS = 1e-5;
                            ^~~~
compilation terminated due to -Wfatal-errors.
```

That's sad because I'm really willing to test exaFMM.

**Comment by rioyokota** [comment]
This error should only happen if you are trying to compile it as c++11 code. What is the version of your g++ compiler?

**Comment by maxlevesque** [comment]
g++ (Ubuntu 6.2.0-7ubuntu11) 6.2.0 20161018
Copyright (C) 2016 Free Software Foundation, Inc.

**Comment by rioyokota** [comment]
g++ 6 and above defaults to -std=gnu++14 instead of -std=gnu++98.
You can get rid of this error by using
./configure CXXFLAGS=-std=gnu++98

**Comment by maxlevesque** [comment]
Works fine, thank you very much. 

Maybe you could put this in your README since this the default for Ubuntu 16.10 (and thus a problem more people will deal with).

Anyway thank you very much ! I will be able to do my little testings :).
